# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Giorgio Delgado
email: gio@perkur.com
description: Tech Enthusiast, Continuous Learner, Entrepreneur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://giorgiodelgado.ca" # the base hostname & protocol for your site
twitter_username: Giorgio_Delgado
github_username:  gDelgado14
pages: [about, forty-eight]

# Build settings
markdown: kramdown
